
package InterfazSym;

import com.formdev.flatlaf.FlatLaf;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import InterfazSym.Datos.*;

public class InicioPrinci extends javax.swing.JFrame {

    public static String NombUsuario;
    public InicioPrinci() {
        
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmInicionS = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarN = new javax.swing.JButton();
        jPassContra = new javax.swing.JPasswordField();
        frmAgregar = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNombreU = new javax.swing.JLabel();
        txtNombreU = new javax.swing.JTextField();
        lblPasswordU = new javax.swing.JLabel();
        txtPasswordU = new javax.swing.JTextField();
        lblCodigoU = new javax.swing.JLabel();
        txtCodigoU = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblUltimoU = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        frmInicionS.setTitle("Iniciar Seción ");
        frmInicionS.setBounds(new java.awt.Rectangle(250, 250, 0, 0));
        frmInicionS.setMinimumSize(new java.awt.Dimension(323, 300));
        frmInicionS.setUndecorated(true);

        jPanel3.setToolTipText("Iniciar Seción ");
        jPanel3.setMinimumSize(new java.awt.Dimension(323, 374));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN");

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Aceptar");
        btnIniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        btnAgregarN.setText("<html>Agregar nuevo<br> .        .   . usuario</html>");
        btnAgregarN.setToolTipText("");
        btnAgregarN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNActionPerformed(evt);
            }
        });

        jPassContra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPassContra.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPassContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPassContra, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout frmInicionSLayout = new javax.swing.GroupLayout(frmInicionS.getContentPane());
        frmInicionS.getContentPane().setLayout(frmInicionSLayout);
        frmInicionSLayout.setHorizontalGroup(
            frmInicionSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInicionSLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frmInicionSLayout.setVerticalGroup(
            frmInicionSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frmAgregar.setTitle("Registrar nuevo usuario");
        frmAgregar.setBounds(new java.awt.Rectangle(400, 315, 0, 0));

        jPanel2.setBackground(null);
        jPanel2.setToolTipText("Registrar nuevo usuario");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("REGISTRAR NUEVO USUARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 20));

        lblNombreU.setText("Nombre de usuario: ");
        jPanel2.add(lblNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel2.add(txtNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

        lblPasswordU.setText("Contraseña:");
        jPanel2.add(lblPasswordU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel2.add(txtPasswordU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, -1));

        lblCodigoU.setBackground(null);
        lblCodigoU.setForeground(null);
        lblCodigoU.setText("Codigo:");
        jPanel2.add(lblCodigoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel2.add(txtCodigoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        btnVolver.setBackground(null);
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 100, 20));

        btnRegistrar.setBackground(null);
        btnRegistrar.setForeground(null);
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblUltimoU.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUltimoU.setText(".........");
        jPanel2.add(lblUltimoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel7.setText("Ultimo Codigo Registrado:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout frmAgregarLayout = new javax.swing.GroupLayout(frmAgregar.getContentPane());
        frmAgregar.getContentPane().setLayout(frmAgregarLayout);
        frmAgregarLayout.setHorizontalGroup(
            frmAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        frmAgregarLayout.setVerticalGroup(
            frmAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazSym/logo-400x400.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        cConnection cn = new cConnection(); // invoca a la clase que conecta
    
           Statement  st = null; 
           ResultSet  rs = null;
           jPassContra.setEchoChar('*');

           String query;

           int band = 0; //bandera para verificación

           String user = txtNombre.getText();
           String passw = jPassContra.getText();

           if("".equals(user))
               JOptionPane.showMessageDialog(null, "Ingrese nombre de usuario");
           else if("".equals(passw))
               JOptionPane.showMessageDialog(null, "Ingrese contraseña");
           else {   

               query = "SELECT * FROM Usuario WHERE NombUser = '"+user+"' AND PassUser = '"+passw+"'";

               try{
                    Connection conexion = cn.ObtenerConexion();

                if(conexion == null){
                    JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos");
                    return;
                }

                st = conexion.createStatement();  
                rs = st.executeQuery(query);

                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"✅ Bienvenido " + user);
                    
                    
                    //guardando el nombre de usuario:
                    Datos.USUARIO = txtNombre.getText();
                    
                    frmInicionS.setVisible(false);
                    
                    Interfaz myInterfaz = new Interfaz();
                    myInterfaz.setVisible(true);
                    myInterfaz.setSize(400,428);
                    FlatLaf.updateUI();
                } else {
                    JOptionPane.showMessageDialog(null,"❌ Usuario o contraseña incorrectos");
                    txtNombre.setText("");
                    jPassContra.setText("");
                    txtNombre.requestFocus();
                }

            } catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "ERROR DE ACCESO: " + ex.getMessage());
            }
                   
           }
           
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnAgregarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNActionPerformed

        frmAgregar.setVisible(true);
        frmAgregar.setSize(400,315);

       
    }//GEN-LAST:event_btnAgregarNActionPerformed

    private void jPassContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassContraActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        frmAgregar.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
 

    cConnection con = new cConnection();

    String codigo = txtCodigoU.getText();
    String nombre = txtNombreU.getText();
    String pass = txtPasswordU.getText();

    if(nombre.equals("") || pass.equals("")){
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        return;
    }

    String sql = "INSERT INTO Usuario (IdUser, NombUser, PassUser) VALUES ("+codigo+", '"+nombre+"', '"+pass+"')";

    try {
        Statement st = con.ObtenerConexion().createStatement();
        int resultado = st.executeUpdate(sql);

        if(resultado > 0){
        JOptionPane.showMessageDialog(null,"✅ Usuario registrado correctamente");
        txtNombreU.setText("");
          txtPasswordU.setText("");
           }else{
            JOptionPane.showMessageDialog(null,"❌ No se pudo registrar");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Error al guardar: " + e.getMessage());
                }
            String query = "SELECT MAX(IdUser) AS IdUser FROM Usuario";

            try {
                Statement st = con.ObtenerConexion().createStatement();
                ResultSet rs = st.executeQuery(query);

                if(rs.next()){
                    int cod = rs.getInt("IdUser") + 1;
                    txtCodigoU.setText(String.valueOf(cod));
                    txtCodigoU.setEditable(false);
                    txtNombreU.requestFocus();
                }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error al obtener código");
            }



    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);

    try {
        // Crear el formulario splash
        final FormSplash sp = new FormSplash(); 
        sp.setVisible(true);

        // Crear el formulario principal que quieres mostrar

        frmInicionS.setSize(347, 378);

        // Hilo que controla la animación del splash
        Thread hilos = new Thread() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {

                    // Texto del porcentaje
                    sp.lblPorcentaje.setText(i + "%");

                    // Estados
                    if(i==10)
                        sp.lblEstado.setText("Cargando Módulos...");
                    else if(i==50)
                        sp.lblEstado.setText("Preparando interfaz...");
                    else if(i==90)
                        sp.lblEstado.setText("Iniciando aplicación...");
                    else if(i==100) {
                        sp.setVisible(false);  // oculta el splash
                        frmInicionS.setVisible(true);  // muestra tu frame
                        FlatLaf.updateUI();
                        frmInicionS.setSize(347, 378);
                    }

                    sp.pgBarraCarga.setValue(i);

                    try { Thread.sleep(30); }
                    catch (InterruptedException ex) {}
                }
            }
        };

        hilos.start();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "ERROR al cargar la aplicación");
    }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioPrinci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarN;
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JFrame frmAgregar;
    private javax.swing.JFrame frmInicionS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassContra;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoU;
    private javax.swing.JLabel lblNombreU;
    private javax.swing.JLabel lblPasswordU;
    private javax.swing.JLabel lblUltimoU;
    private javax.swing.JTextField txtCodigoU;
    public javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JTextField txtPasswordU;
    // End of variables declaration//GEN-END:variables
}
